import '../domain/all_domain.dart';

class DefaultUser {
  static User myself = User(
    username: 'HandleX',
    email: "HandleX@gmail.com",
    password: "123456",
    bio: "I really wanna be Google Software Engineer",
    xh: 123456,
    postImageUrl: "images/school_pic.jpg",
    userImageUrl: "images/myself.bmp",
    school: "野鸡大学软件学院",
    postCount: 23,
    followingCount: 995,
    followersCount: 483,
  );

  static final User xp = User(
    username: '小胖',
    email: "xp@outlook.com",
    password: "123456",
    bio: "2023已上岸 - 南京大学人工智能学院在读研究生",
    xh: 111111,
    postImageUrl: "images/408score.png",
    userImageUrl: "images/xp.bmp",
    school: "南京大学人工智能学院",
    postCount: 20,
    followingCount: 765,
    followersCount: 3456,
  );

  static final User dcx = User(
    username: 'dcx',
    email: "dcx@gmail.com",
    password: "123456",
    bio: "劝君猛省莫徘徊",
    xh: 666666,
    postImageUrl: "images/csu.jpeg",
    userImageUrl: "images/dp.bmp",
    school: "中南大学新能源学院",
    postCount: 65,
    followingCount: 765,
    followersCount: 235,
  );

  static final User wq = User(
    username: 'wq',
    email: "wq@gmail.com",
    password: "123456",
    bio: "拿下",
    xh: 123456,
    postImageUrl: "images/lake.jpg",
    userImageUrl: "images/wq.bmp",
    school: "山东大学微电子学院",
    postCount: 11,
    followingCount: 124,
    followersCount: 214,
  );
}

class PostData {
  static Post initPost = Post(
    username: 'Null',
    school: "门头沟学院",
    content: "",
    userImageUrl: 'images/myself.bmp',
    postImageUrl: '',
    likes: 0,
    isLiked: false,
    comments: 0,
    type: 0,
    user: DefaultUser.myself,
  );
  static List<Post> posts = [
    Post(
      username: 'HandleExe',
      school: "野鸡大专人工智能学院",
      content: "恭喜同学们考上研究生",
      userImageUrl: 'images/myself.bmp',
      postImageUrl: '',
      likes: 4,
      isLiked: false,
      comments: 9,
      type: 0,
      user: DefaultUser.myself,
    ),
    Post(
      username: '小胖',
      school: "南京大学人工智能学院",
      content: "一年的努力还是没有白费的，哈哈，南大，我来了",
      userImageUrl: 'images/xp.bmp',
      postImageUrl: 'images/408score.png',
      likes: 23,
      isLiked: true,
      comments: 9,
      type: 0,
      user: DefaultUser.xp,
    ),
    Post(
      username: 'der',
      school: "中南大学新能源学院",
      content: "哈哈, 就快下一阶段咯",
      userImageUrl: 'images/dp.bmp',
      postImageUrl: 'images/csu.jpeg',
      likes: 37,
      isLiked: false,
      comments: 9,
      type: 0,
      user: DefaultUser.dcx,
    ),
    Post(
      username: 'wq',
      school: "山东大学微电子学院",
      content: "",
      userImageUrl: 'images/wq.bmp',
      postImageUrl: 'images/lake.jpg',
      likes: 37,
      isLiked: false,
      comments: 9,
      type: 0,
      user: DefaultUser.wq,
    ),
  ];
  static List<Post> commentPosts = [
    Post(
      username: 'HandleExe',
      school: "野鸡大专人工智能学院",
      content: "不要慌，不要慌",
      userImageUrl: 'images/myself.bmp',
      postImageUrl: '',
      likes: 0,
      isLiked: true,
      comments: 9,
      type: 1,
      user: DefaultUser.myself,
    ),
    Post(
      username: '小胖',
      school: "野鸡大专人工智能学院",
      content: "呵呵",
      userImageUrl: 'images/xp.bmp',
      postImageUrl: '',
      likes: 0,
      isLiked: false,
      comments: 0,
      type: 1,
      user: DefaultUser.xp,
    ),
    Post(
      username: '小胖',
      school: "南京大学人工智能学院",
      content: "作甚么呢这是",
      userImageUrl: 'images/xp.bmp',
      postImageUrl: 'images/408score.png',
      likes: 23,
      isLiked: true,
      comments: 9,
      type: 1,
      user: DefaultUser.xp,
    ),
    Post(
      username: 'der',
      school: "中南大学新能源学院",
      content: "哈哈, 乐",
      userImageUrl: 'images/dp.bmp',
      postImageUrl: 'images/csu.jpeg',
      likes: 37,
      isLiked: false,
      comments: 16,
      type: 1,
      user: DefaultUser.dcx,
    ),
    Post(
      username: 'wq',
      school: "山东大学微电子学院",
      content: "...6",
      userImageUrl: 'images/wq.bmp',
      postImageUrl: 'images/lake.jpg',
      likes: 37,
      isLiked: false,
      comments: 16,
      type: 1,
      user: DefaultUser.wq,
    ),
    Post(
      username: 'wq',
      school: "山东大学微电子学院",
      content: "@小胖 牛逼",
      userImageUrl: 'images/wq.bmp',
      postImageUrl: 'images/lake.jpg',
      likes: 37,
      isLiked: false,
      comments: 16,
      type: 1,
      user: DefaultUser.wq,
    ),
    Post(
      username: '小胖',
      school: "南京大学人工智能学院",
      content: "@wq 哈哈",
      userImageUrl: 'images/xp.bmp',
      postImageUrl: 'images/408score.png',
      likes: 23,
      isLiked: false,
      comments: 9,
      type: 1,
      user: DefaultUser.xp,
    ),
  ];
}
